Learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('Learning_logs.urls', namespace='Learning_logs')),
]

Learning_logs/urls.py
"""定义Learning_logs的url模式"""

from django.conf.urls import url

from . import views

urlpatterns = [
    # Main page
    url(r'^$', views.index, name='index'),

    # Show all topics
    url(r'^topics/$', views.topics, name='topics'),

    # Special topic to show
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
]

Learning_logs/models.py
from django.db import models


class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """具体相关"""
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    # 复数显示的名字
    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""
        if len(self.text) > 50:
            return self.text[:50] + "..."
        else:
            return self.text

Learning_logs/views.py
from django.shortcuts import render

from .models import Topic


def index(request):
    """Page of Learning_log"""
    return render(request, 'Learning_logs/index.html')


def topics(request):
    """Show all topics"""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'Learning_logs/topics.html', context)


def topic(request, topic_id):
    """Show special topic"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'Learning_logs/topic.html', context)

templates/Learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<p>
  <a href="{% url 'Learning_logs:index' %}">Learning Log</a> -
  <a href="{% url 'Learning_logs:topics' %}">Topics</a>
</p>

{% block content %}{% endblock content %}
</body>
</html>

templates/Learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>YiFan_Chen</title>
</head>
<body>
{% extends "Learning_logs/base.html" %}

{% block content %}
  <p>Learning_logs help you track of your learning and life, for any respect you're learn about.</p>
{% endblock content %}

<p>The second line.</p>
</body>
</html>

templates/Learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Special_Topic</title>
</head>
<body>
{% extends 'Learning_logs/base.html' %}

{% block content %}

  <p>Topic:{{ topic }}</p>

  <p>Entries:</p>
  <ul>
      {% for entry in entries %}
      <li>
          <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
          <p>{{ entry.text|linebreaks }}</p>
      </li>

      {% empty %}
          <li>
            There are no entries for this topic yet.
          </li>
      {% endfor %}
  </ul>

{% endblock content %}
</body>
</html>

templates/Learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>YiFan_Chen</title>
</head>
<body>
{% extends "Learning_logs/base.html" %}

{% block content %}
<p>
    Topics
</p>

<ul>
    {% for topic in topics %}
        <li>
          <a href="{% url 'Learning_logs:topic' topic_id %}">{{ topic }}</a>
        </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
</ul>
{% endblock content %}
</body>
</html>